# This compose file is for locally testing the backup sidecar solution

services:
  pds:
    container_name: pds
    build:
      context: pds
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      db_backup_sidecar:
        condition: service_healthy
      file_backup_sidecar:
        condition: service_healthy
    volumes:
      - pds-data:/pds
      - $HOME/.aws/:/home/.aws/:ro
    cpu_count: 1
    mem_limit: 2GB
    healthcheck:
      test: [ "CMD-SHELL", "node -e 'fetch(`http://localhost:3000/xrpc/_health`).then(()=>process.exitCode = 0).catch(()=>process.exitCode = 1)'"]
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 1m
      start_interval: 5s
    environment:
      HOME: "/home"
      PDS_HOSTNAME: "doesnotexist.com"
      PDS_PORT: "3000"
      PDS_DATA_DIRECTORY: '/pds'
      PDS_PLC_ROTATION_KEY_KMS_KEY_ID: "${PDS_PLC_ROTATION_KEY_KMS_KEY_ID}"
      AWS_REGION: 'us-east-2'
      AWS_DEFAULT_REGION: 'us-east-2'
      PDS_BLOBSTORE_S3_REGION: 'us-east-2'
      PDS_BLOBSTORE_S3_BUCKET: "${PDS_BLOBSTORE_S3_BUCKET}"
      PDS_BLOB_UPLOAD_LIMIT: '52428800'
      PDS_DID_PLC_URL: 'https://plc.directory'
      PDS_BSKY_APP_VIEW_URL: 'https://api.bsky.app'
      PDS_BSKY_APP_VIEW_DID: 'did:web:api.bsky.app'
      PDS_REPORT_SERVICE_URL: 'https://mod.bsky.app'
      PDS_REPORT_SERVICE_DID: 'did:plc:ar7c4by46qjdydhdevvrndac'
      PDS_CRAWLERS: 'https://bsky.network'
      PDS_ADMIN_PASSWORD: "${PDS_ADMIN_PASSWORD}"
      PDS_JWT_SECRET: "${PDS_JWT_SECRET}"
      LOG_ENABLED: true
      PDS_EMAIL_FROM_ADDRESS: 'hello@doesnotexist.com'
      SMTP_HOST: 'localhost'
      SMTP_MAIL_USERNAME: 'fake'
      SMTP_MAIL_PASSWORD: 'fa//ke'

  db_backup_sidecar:
    container_name: litestream
    image: litestream
    build:
      context: pds-litestream
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - pds-data:/sync
      - $HOME/.aws/:/root/.aws/:ro
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 1m
      start_interval: 5s
    stop_signal: SIGTERM
    stop_grace_period: 1m
    environment:
      AWS_REGION: 'us-east-2'
      AWS_DEFAULT_REGION: 'us-east-2'
      S3_PATH: "s3://${PDS_BACKUP_S3_BUCKET}/litestream-replication"
      LOCAL_PATH: '/sync'

  file_backup_sidecar:
    container_name: s3_file_sync
    image: s3_file_sync
    build:
      context: pds-s3-file-sync
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      db_backup_sidecar:
        condition: service_healthy
    volumes:
      - pds-data:/sync
      - $HOME/.aws/:/root/.aws/:ro
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 1m
      start_interval: 5s
    stop_signal: SIGTERM
    stop_grace_period: 1m
    environment:
      AWS_REGION: 'us-east-2'
      AWS_DEFAULT_REGION: 'us-east-2'
      S3_PATH: "s3://${PDS_BACKUP_S3_BUCKET}/file-backup/actors"
      LOCAL_PATH: '/sync/actors'

volumes:
  pds-data:
